#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           a,             tmotorVex393_HBridge, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port10,          b,             tmotorVex393_HBridge, openLoop, encoderPort, I2C_2)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Cone_Lifter_Interface.c"
//#include "JoyStickMap.h"
//#include "RobotMap.h"
#include "MotorConstants.h"

task main()
{
	initializeCLifterMotors(a,b,IME_TICKS_PER_DEG);

	startTask(cLifterControlTask, main+1);

	for(;;)
	{
		wait1Msec(5);
	}
}
