#pragma config(Motor,  port1,           left,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,          right,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "DriverInterface.c"

task main()
{

	initializeDriveMotors(left, right);

	startTask(driveControlTask, main + 1);

	for (;;)
	{
		wait1Msec(1000);
	}


}
