#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           One,           tmotorVex393_HBridge, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port6,           left,          tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Goal_Interface.c"
#include "MotorConstants.h"
task main()
{
	//slaveMotor(right, left);
	initializeGoalLifterMotors(One, IME_TICKS_PER_DEG);

	startTask(goalLifterControlTask, main+1);

	for(;;)
	{
		wait1Msec(1000);
	}


}
