#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           claw,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           left,          tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,           right,         tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port4,           arm,           tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task PosArmControl()
{
	float setPoint=0.0;
	float position=0.0;
	float k=2.0;
	float minVal=0;
	float maxVal=270.0 * 7.0;
	float error=0.0;

	resetMotorEncoder(arm);

	for(;;)
	{
		int joy = getJoystickValue(Ch2Xmtr2);

		long enc = getMotorEncoder(arm);

		if( (abs(joy)>20)
		&&
			 (((setPoint >= maxVal) && (joy<0))
		||  ((setPoint <= minVal) && (joy>0))
		||  ((setPoint > minVal) && (setPoint<maxVal))))
		{
			setPoint=(float)enc/1.742;
		  motor[arm]=-joy;
		}
    else
    {
		  if(setPoint>maxVal)
		  {
		  	setPoint=maxVal;
		  }
		  else if(setPoint<minVal)
		  {
				setPoint=minVal;
			}
			position = (float) enc/1.742;
			error=setPoint-position;
			motor[arm]=-error*k;
		}

		wait1Msec(5);
	}
}

task main()
{
	//// Use Motors & Sensor Setup to Configure Your Robot!
	//setPIDforMotor(port4, true);
	enableCompetitionMode();
	startTask(PosArmControl,main+1);
	for (;;) {
		//// Place Autonomous Commands Below
		if (getCompetitionAutonomous() == true) {
		}
		//// Place Remote Control Commands Below
		if (getCompetitionDriverControl() == true)
		{
			arcadeControl(Ch3, Ch1, 30);
			buttonControl(port1, Btn5UXmtr2, Btn5DXmtr2, 60);
		}

		wait1Msec(5);

	}

}
